version: '3.8'

services:
  mysql:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loans

  # node-app:
  #   build:
  #     context: .
  #   container_name: node-app
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DB_HOST: mysql
  #     DB_PORT: 3306
  #     DB_USER: root
  #     DB_PASSWORD: password
  #     DB_NAME: loans
  #     JWT_SECRET: mysecretkey
